var jTransform = '{ "version": { '
   + '        "name": "none", '
   + '        "version": "harvestInformation.version" '
   + '     },'
   + '      "contact": "metadataProperties.metadataContact.relatedAgent.agentRole",'
   + '      "metadata": { '
   + '        "metadataInfo": {'
   + '          "metadataIdentifier": {'
   + '            "identifier": "harvestInformation.originalFileIdentifier",'
   + '            "type": "none"'
   + '          }'
   + '        }'
   + '       },'
   + '      "resourceInfo": { '
   + '          "resourceType": "linkContentResourceType", '
   + '          "citation": { '
   + '            "title": "resourceDescription.resourceTitle", '
   + '            "date":  "resourceDescription.citationDates.EventDateObject.dateTime"  '
   + '          },'
   + '          "pointOfContact": [], '
   + '          "abstract": "resourceDescription.resourceDescription", '
   + '          "status": "null",'
   + '          "language": [{"eng":"USA"}],'
   + '          "extent": [{"description" : "null",'
   + '              "geographicElement" : { ' 
   + '                "type": "null", '
   + '                "bbox": [ '
   + '        "resourceDescription.geographicExtent.westBoundLongitude", '
   + '        "resourceDescription.geographicExtent.northBoundLatitude", '
   + '        "resourceDescription.geographicExtent.esstBoundLongitude", '
   + '        "resourceDescription.geographicExtent.southBoundLatitude" '
   + '                       ] '
   + '             } '
   + '         }]'
   + '      }'
   + '   }';
 //  + '   "dataDictionary": [] }';